[versions]
minSdk = '26'  # min for activity.isRequestPinAppWidgetSupported
compileSdk = '34'

# Plugins
agp = "8.2.0"
kotlin = '1.9.21'
java = '17'
ksp = "1.9.21-1.0.16"
triplet-play = '3.8.6'
hilt = '2.50'

# Libraries
compose-compiler = '1.5.7'
compose-tooling = '1.5.4'
lifecycle = "2.6.2"
okhttp = "4.12.0"
compose-lint-checks = "1.2.0"
kotlinxCollectionsImmutable = "0.3.7"

[libraries]

# Owned
androidutils = 'com.github.w2sv:AndroidUtils:0.3.25-rc2'
colorpicker = 'com.github.w2sv:Compose-Color-Picker-Bundle:1.0.0-rc9'

# Androidx
androidx-appcompat = 'androidx.appcompat:appcompat:1.6.1'
androidx-core = 'androidx.core:core-ktx:1.12.0'
androidx-localbroadcastmanager = 'androidx.localbroadcastmanager:localbroadcastmanager:1.1.0'
androidx-splashscreen = 'androidx.core:core-splashscreen:1.0.1'
androidx-lifecycle-runtime = { module = 'androidx.lifecycle:lifecycle-runtime-ktx', version.ref = 'lifecycle' }
androidx-workmanager = 'androidx.work:work-runtime-ktx:2.9.0'
androidx-datastore-preferences = 'androidx.datastore:datastore-preferences:1.0.0'

# .Compose
androidx-compose-bom = "androidx.compose:compose-bom:2024.01.00"
androidx-compose-material3 = 'androidx.compose.material3:material3:1.1.2'
androidx-compose-ui = { module = 'androidx.compose.ui:ui', version.ref = 'compose-tooling' }
androidx-compose-ui-tooling-preview = { module = 'androidx.compose.ui:ui-tooling-preview', version.ref = 'compose-tooling' }
androidx-compose-ui-tooling = { module = 'androidx.compose.ui:ui-tooling', version.ref = 'compose-tooling' }
androidx-compose-activity = 'androidx.activity:activity-compose:1.8.2'
androidx-compose-viewmodel = { module = 'androidx.lifecycle:lifecycle-viewmodel-compose', version.ref = 'lifecycle' }
androidx-lifecycle-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }

# Google
google-material = 'com.google.android.material:material:1.11.0'
accompanist-permissions = "com.google.accompanist:accompanist-permissions:0.32.0"

# .Hilt
google-hilt = { module = 'com.google.dagger:hilt-android', version.ref = 'hilt' }
google-hilt-compiler = { module = 'com.google.dagger:hilt-android-compiler', version.ref = 'hilt' }
androidx-hilt-work = "androidx.hilt:hilt-work:1.1.0"

# Other
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinxCollectionsImmutable" }
slimber = 'com.github.PaulWoitaschek:Slimber:2.0.0'
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
compose-lint-checks = { module = "com.slack.lint.compose:compose-lint-checks", version.ref = "compose-lint-checks" }

# Plugins
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }

[plugins]
application = { id = 'com.android.application', version.ref = 'agp' }
library = { id = 'com.android.library', version.ref = 'agp' }
kotlin = { id = 'org.jetbrains.kotlin.android', version.ref = 'kotlin' }
hilt = { id = 'com.google.dagger.hilt.android', version.ref = 'hilt' }
play = { id = 'com.github.triplet.play', version.ref = 'triplet-play' }
ksp = { id = "com.google.devtools.ksp", version.ref = 'ksp' }

# Plugins defined by the project
wifiwidget-library = { id = "wifiwidget.library", version = "unspecified" }
wifiwidget-hilt = { id = "wifiwidget.hilt", version = "unspecified" }