[versions]
# SDKs
minSdk = "26"  # min for activity.isRequestPinAppWidgetSupported
compileSdk = "34"

# Plugins
agp = "8.3.2"
kotlin = "1.9.23"
java = "17"
ksp = "1.9.23-1.0.20"
triplet-play = "3.9.1"
hilt = "2.51.1"
baselineprofile = "1.2.4"
protobuf-plugin = "0.9.4"

compose-compiler = "1.5.12"

# Libraries
androidx-activity-compose = "1.9.0"
compose-tooling = "1.6.6"
compose-material3 = "1.2.1"
lifecycle = "2.7.0"
okhttp = "4.12.0"
compose-lint-checks = "1.3.1"
kotlinxCollectionsImmutable = "0.3.7"
junit = "1.1.5"
benchmarkMacroJunit4 = "1.2.4"
profileinstaller = "1.3.1"
runner = "1.5.2"
protobuf = "4.26.1"
datastore = "1.1.0"
composed = "0.0.3-rc2"

[libraries]

# Owned
androidutils = "com.github.w2sv:AndroidUtils:0.3.30-rc7"
colorpicker = "com.github.w2sv:Compose-Color-Picker-Bundle:1.0.0-rc9"
kotlinutils = "com.github.w2sv:KotlinUtils:0.0.8-rc1"
composed = { module = "com.github.w2sv.Composed:composed", version.ref = "composed" }
composed-permissions = { module = "com.github.w2sv.Composed:permissions", version.ref = "composed" }

# Androidx
androidx-appcompat = "androidx.appcompat:appcompat:1.6.1"
androidx-core = "androidx.core:core-ktx:1.13.1"
androidx-localbroadcastmanager = "androidx.localbroadcastmanager:localbroadcastmanager:1.1.0"
androidx-splashscreen = "androidx.core:core-splashscreen:1.0.1"
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-workmanager = "androidx.work:work-runtime-ktx:2.9.0"
androidx-datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }

# .Compose
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-material3" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose-tooling" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose-tooling" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose-tooling" }
androidx-compose-activity = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
androidx-compose-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-lifecycle-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }

# .Benchmarking
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit" }
androidx-benchmark-macro-junit4 = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "benchmarkMacroJunit4" }
androidx-profileinstaller = { group = "androidx.profileinstaller", name = "profileinstaller", version.ref = "profileinstaller" }
androidx-runner = { group = "androidx.test", name = "runner", version.ref = "runner" }

# Google
google-material = "com.google.android.material:material:1.11.0"
google-accompanist-permissions = "com.google.accompanist:accompanist-permissions:0.34.0"
google-hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
google-hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
protobuf-kotlin-lite = { group = "com.google.protobuf", name = "protobuf-kotlin-lite", version.ref = "protobuf" }
protobuf-protoc = { group = "com.google.protobuf", name = "protoc", version.ref = "protobuf" }

# Other
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinxCollectionsImmutable" }
slimber = "com.github.PaulWoitaschek:Slimber:2.0.0"
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
compose-lint-checks = { module = "com.slack.lint.compose:compose-lint-checks", version.ref = "compose-lint-checks" }

# Plugins
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }

[plugins]
application = { id = "com.android.application", version.ref = "agp" }
library = { id = "com.android.library", version.ref = "agp" }
androidTest = { id = "com.android.test", version.ref = "agp" }
baselineprofile = { id = "androidx.baselineprofile", version.ref = "baselineprofile" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
play = { id = "com.github.triplet.play", version.ref = "triplet-play" }
protobuf = { id = "com.google.protobuf", version.ref = "protobuf-plugin" }

# Plugins defined by the project
wifiwidget-library = { id = "wifiwidget.library", version = "unspecified" }
wifiwidget-hilt = { id = "wifiwidget.hilt", version = "unspecified" }
