[versions]
minSdk = '26'  # min for activity.isRequestPinAppWidgetSupported
compileSdk = '33'

compose-compiler = '1.4.0'
compose-tooling = '1.3.3'
agp = '7.4.1'
kotlin = '1.8.0'
hilt = '2.44.2'
junit = '5.9.2'
lifecycle = '2.5.1'

[libraries]

# owned
typedpreferences = 'com.github.w2sv:TypedPreferences:1.0.1-rc2'
androidutils = 'com.github.w2sv:AndroidUtils:0.0.16-rc1'
permissionhandler = 'com.github.w2sv:PermissionHandler:1.0.0-rc3'

# androidx
androidx-appcompat = 'androidx.appcompat:appcompat:1.7.0-alpha01'
androidx-core = 'androidx.core:core-ktx:1.9.0'
androidx-localbroadcastmanager = 'androidx.localbroadcastmanager:localbroadcastmanager:1.1.0'
androidx-splashscreen = 'androidx.core:core-splashscreen:1.0.0-beta02'
androidx-lifecycle-runtime = { module = 'androidx.lifecycle:lifecycle-runtime-ktx', version.ref = 'lifecycle' }
androidx-workmanager = "androidx.work:work-runtime-ktx:2.7.1"
androidx-compose-bom = 'androidx.compose:compose-bom:2023.01.00'
androidx-compose-material3 = 'androidx.compose.material3:material3:1.0.1'
androidx-compose-ui = { module = 'androidx.compose.ui:ui', version.ref = 'compose-tooling' }
androidx-compose-ui-tooling-preview = { module = 'androidx.compose.ui:ui-tooling-preview', version.ref = 'compose-tooling' }
androidx-compose-ui-tooling = { module = 'androidx.compose.ui:ui-tooling', version.ref = 'compose-tooling' }
androidx-compose-activity = 'androidx.activity:activity-compose:1.6.1'
androidx-compose-viewmodel = { module = 'androidx.lifecycle:lifecycle-viewmodel-compose', version.ref = 'lifecycle' }

# google
google-material = 'com.google.android.material:material:1.8.0'
google-hilt = { module = 'com.google.dagger:hilt-android', version.ref = 'hilt' }
google-hilt-kapt = { module = 'com.google.dagger:hilt-android-compiler', version.ref = 'hilt' }

# other
slimber = 'com.github.PaulWoitaschek:Slimber:2.0.0'

[plugins]
application = { id = 'com.android.application', version.ref = 'agp' }
library = { id = 'com.android.library', version.ref = 'agp' }
kotlin = { id = 'org.jetbrains.kotlin.android', version.ref = 'kotlin' }
hilt = { id = 'com.google.dagger.hilt.android', version.ref = 'hilt' }