[versions]
# SDKs
minSdk = "26"  # min for activity.isRequestPinAppWidgetSupported
compileSdk = "34"

# Plugins
agp = "8.7.1"
kotlin = "2.0.20"
java = "17"
ksp = "2.0.20-1.0.25"
triplet-play = "3.11.0"
hilt = "2.52"
baselineprofile = "1.3.3"
protobuf-plugin = "0.9.4"

# Libraries
androidx-activity-compose = "1.9.3"
compose-tooling = "1.7.4"
compose-material3 = "1.3.0"
lifecycle = "2.8.7"
okhttp = "4.12.0"
compose-lint-checks = "1.4.2"
kotlinxCollectionsImmutable = "0.3.8"
junit = "1.2.1"
benchmarkMacroJunit4 = "1.3.3"
profileinstaller = "1.4.1"
runner = "1.6.2"
protobuf = "4.28.2"
datastore = "1.1.1"
composed = "0.0.5-rc2"
compose-destinations = "2.0.0-beta01"
hiltNavigationCompose = "1.2.0"
datastoreutils = "0.0.4-rc1"
kotlinutils = "0.1.3-rc1"

[libraries]

# w2sv
w2sv-androidutils = "com.github.w2sv:AndroidUtils:0.4.2-rc2"
w2sv-colorpicker = "com.github.w2sv:Compose-Color-Picker-Bundle:1.0.0-rc9"
w2sv-kotlinutils = { module = "com.github.w2sv:KotlinUtils", version.ref = "kotlinutils" }
w2sv-reversiblestate = "com.github.w2sv:ReversibleStateKt:0.0.5-rc1"
w2sv-datastoreutils-preferences = { module = "com.github.w2sv.DataStoreUtils:preferences", version.ref = "datastoreutils" }
w2sv-datastoreutils-datastoreflow = { module = "com.github.w2sv.DataStoreUtils:datastoreflow", version.ref = "datastoreutils" }
w2sv-composed = { module = "com.github.w2sv.Composed:composed", version.ref = "composed" }
w2sv-composed-permissions = { module = "com.github.w2sv.Composed:permissions", version.ref = "composed" }
w2sv-composeWheelPicker = "com.github.w2sv:compose-wheel-picker:0.0.2-rc1"

# Androidx
androidx-appcompat = "androidx.appcompat:appcompat:1.7.0"
androidx-core = "androidx.core:core-ktx:1.13.1"
androidx-splashscreen = "androidx.core:core-splashscreen:1.0.1"
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-workmanager = "androidx.work:work-runtime-ktx:2.9.1"
androidx-datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }

# .Compose
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-material3" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose-tooling" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose-tooling" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose-tooling" }
androidx-compose-activity = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
androidx-compose-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-lifecycle-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }

# .Benchmarking
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit" }
androidx-benchmark-macro-junit4 = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "benchmarkMacroJunit4" }
androidx-profileinstaller = { group = "androidx.profileinstaller", name = "profileinstaller", version.ref = "profileinstaller" }
androidx-runner = { group = "androidx.test", name = "runner", version.ref = "runner" }

# Google
google-material = "com.google.android.material:material:1.12.0"
google-accompanist-permissions = "com.google.accompanist:accompanist-permissions:0.34.0"
google-hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
google-hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
protobuf-kotlin-lite = { group = "com.google.protobuf", name = "protobuf-kotlin-lite", version.ref = "protobuf" }
protobuf-protoc = { group = "com.google.protobuf", name = "protoc", version.ref = "protobuf" }

# Other
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinxCollectionsImmutable" }
slimber = "com.github.PaulWoitaschek:Slimber:2.0.0"
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
compose-lint-checks = { module = "com.slack.lint.compose:compose-lint-checks", version.ref = "compose-lint-checks" }
compose-destinations = { module = "io.github.raamcosta.compose-destinations:core", version.ref = "compose-destinations" }
compose-destinations-ksp = { module = "io.github.raamcosta.compose-destinations:ksp", version.ref = "compose-destinations" }

# Plugins
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-test = { id = "com.android.test", version.ref = "agp" }
kotlin-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
baselineprofile = { id = "androidx.baselineprofile", version.ref = "baselineprofile" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
play = { id = "com.github.triplet.play", version.ref = "triplet-play" }
protobuf = { id = "com.google.protobuf", version.ref = "protobuf-plugin" }

# Project plugins
wifiwidget-library = { id = "wifiwidget.library", version = "unspecified" }
wifiwidget-hilt = { id = "wifiwidget.hilt", version = "unspecified" }
