[versions]
minSdk = '26'
compileSdk = '33'

compose-compiler = '1.4.0'
gradle-plugin = '7.4.0'
kotlin = '1.8.0'
hilt = '2.44.2'
junit = '5.9.2'
lifecycle = '2.6.0-alpha05'

[libraries]
# owned
typedpreferences = 'com.github.w2sv:TypedPreferences:1.0.0'
androidutils = 'com.github.w2sv:AndroidUtils:0.0.15-rc2'

# androidx
androidx-appcompat = 'androidx.appcompat:appcompat:1.6.0'
androidx-core = 'androidx.core:core-ktx:1.9.0'
androidx-splashscreen = 'androidx.core:core-splashscreen:1.0.0-beta02'
androidx-compose-activity = 'androidx.activity:activity-compose:1.6.1'
androidx-compose-viewmodel = { module = 'androidx.lifecycle:lifecycle-viewmodel-compose', version.ref = 'lifecycle' }
androidx-lifecycle-runtime = { module = 'androidx.lifecycle:lifecycle-runtime-ktx', version.ref = 'lifecycle' }

# google
google-hilt = { module = 'com.google.dagger:hilt-android', version.ref = 'hilt' }
google-hilt-kapt = { module = 'com.google.dagger:hilt-android-compiler', version.ref = 'hilt' }

# other
slimber = 'com.github.PaulWoitaschek:Slimber:2.0.0'